test: acitons添加过滤

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,10 +17,20 @@ jobs:
           fetch-depth: 0
           ref: ${{ github.event.pull_request.head.sha }}
 
+      # 检查是否有 /translation 目录下的更改
+      - name: Check translation changes
+        run: |
+          if git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^translation/'; then
+            echo "Translation changes detected, continuing."
+          else
+            echo "No translation changes detected, aborting."
+            exit 1
+          fi
+
       # 获取修改文件路径
       - name: Get modify filenames
         run: |
-          git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^translation/' > modify_files.txt
+          git diff --diff-filter=M --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep '^translation/' > modify_files.txt
           cat modify_files.txt
 
       # 发送请求测试
